#!/usr/bin/env bash
set -euo pipefail

# Phase 1 of 3 for vendoring the ADOT Node.js Lambda layer from source.
#
# This machine can resolve which exact zips are needed (small, metadata-only
# GitHub API calls) but is not the one that downloads them - that's a
# separate team/process. This script only figures out and records the
# download URLs; it fetches no zip content itself.
#
#   Phase 1 (this script): resolve exact commit SHAs -> write a download
#                           manifest.
#   Phase 2 (another team): download each URL in the manifest, save it under
#                           otel-build-inputs/<filename> exactly as named,
#                           and add those files to this repo.
#   Phase 3 (build-otel-layer.sh): once the zips are staged in
#                           otel-build-inputs/, build the layer from them -
#                           entirely offline, no network access at all.
#
# Prerequisites: curl, jq.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/otel-layer-download-manifest.txt"
AWS_OTEL_LAMBDA_REF="${AWS_OTEL_LAMBDA_REF:-main}"

for tool in curl jq; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "Missing required tool: $tool" >&2
    exit 1
  }
done

echo "Resolving aws-observability/aws-otel-lambda @ ${AWS_OTEL_LAMBDA_REF}..."
AWS_OTEL_LAMBDA_SHA=$(curl -sL \
  "https://api.github.com/repos/aws-observability/aws-otel-lambda/commits/${AWS_OTEL_LAMBDA_REF}" \
  | jq -r '.sha')

echo "Resolving the pinned opentelemetry-lambda submodule commit..."
SUBMODULE_SHA=$(curl -sL \
  "https://api.github.com/repos/aws-observability/aws-otel-lambda/contents/opentelemetry-lambda?ref=${AWS_OTEL_LAMBDA_SHA}" \
  | jq -r '.sha')

cat > "$MANIFEST" <<EOF
# ADOT layer source download manifest
# Generated by resolve-otel-layer-urls.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Hand this off to the team that performs downloads. For each row below,
# download <url> and save it as otel-build-inputs/<filename> (exact name),
# then add those files to this repo. Once staged there, build-otel-layer.sh
# performs the actual build entirely offline - no network access needed.
#
# filename	url
aws-otel-lambda.zip	https://github.com/aws-observability/aws-otel-lambda/archive/${AWS_OTEL_LAMBDA_SHA}.zip
opentelemetry-lambda.zip	https://github.com/open-telemetry/opentelemetry-lambda/archive/${SUBMODULE_SHA}.zip
EOF

echo "✓ Wrote ${MANIFEST}"
echo "  Hand it to the download team; they should stage the two zips under"
echo "  ${SCRIPT_DIR}/otel-build-inputs/ before build-otel-layer.sh is run."
